# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 21:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20171017_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('IA', 'InActive'), ('C', 'Closed')], default='A', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['name', 'customer'], name='api_project_name_40e8d6_idx'),
        ),
    ]
