# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171017_2133'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='api_task_name_f6f01a_idx',
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['name', 'project'], name='api_task_name_0bdbe3_idx'),
        ),
    ]
