# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171017_2133'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='api_project_name_40e8d6_idx',
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['name', 'customer'], name='api_project_name_1d3832_idx'),
        ),
    ]
