# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171018_0130'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='timeentry',
            name='api_timeent_name_1af91a_idx',
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['name', 'user_id'], name='api_timeent_name_babad9_idx'),
        ),
    ]
